keymap:
  windowmgr:
    action:
      minimize: meta+minus
      toggle_maximize: ctrl+meta+alt+return
      close: meta+esc
      resize: ctrl+meta+comma

    position:
      centre: ctrl+meta+alt+period
      lower_screen: ctrl+meta+alt+M
      upper_screen: ctrl+meta+alt+U
      right_middle: ctrl+meta+alt+3
      top_right: ctrl+meta+alt+4
      top_middle: ctrl+meta+alt+5
      top_left: ctrl+meta+alt+6
      left_middle: ctrl+meta+alt+7
      bottom_left: ctrl+meta+alt+8
      bottom_middle: ctrl+meta+alt+9
      bottom_right: ctrl+meta+alt+0

    move:
      fast_left: ctrl+meta+alt+left
      slow_left: shift+ctrl+meta+alt+left
      fast_right: ctrl+meta+alt+right
      slow_right: shift+ctrl+meta+alt+right
      fast_up: ctrl+meta+alt+up
      slow_up: shift+ctrl+meta+alt+up
      fast_down: ctrl+meta+alt+down
      slow_down: shift+ctrl+meta+alt+down

workspaces:
  base:
    Directory Opus:
      location: C:\Packages\DOpus
      executable: dopus.exe
      args: NOAUTOLISTER STARTUP
      position: ~
      toggle window: ~
      window identifier: ~

    Obsidian:
      location: C:\Program Files\Obsidian
      executable: Obsidian.exe
      args: ~
      position: ~
      toggle window: ~
      window identifier: ~

    Todoist:
      location: C:\Users\Arindam\AppData\Local\Programs\todoist
      executable: Todoist.exe
      args: ~
      position: ~
      toggle window: ~
      window identifier: ~

    Greenshot:
      location: C:\Program Files\Greenshot
      executable: Greenshot.exe
      args: ~
      position: ~
      toggle window: ~
      window identifier: ~

    CopyQ:
      location: C:\Users\biswas02\AppData\Local\Programs\copyq
      executable: copyq.exe
      args: ~
      position: ~
      toggle window: ~
      window identifier: ~

    Everything:
      location: C:\Program Files\Everything
      executable: Everything.exe
      args: -startup
      position: ~
      toggle window: ~
      window identifier: ~

    PowerToys:
      location: C:\Packages\PowerToys
      executable: PowerToys.exe
      args: ~
      position: ~
      toggle window: ~
      window identifier: ~

    Windows Terminal:
      location: C:\Users\biswas02\AppData\Local\Microsoft\WindowsApps
      executable: wt.exe
      args: ~
      position: bottom_middle
      toggle window: ctrl+meta+alt+comma
      window identifier: WindowsTerminal.exe

    AgendaDashboard:
      location: C:\Users\Arindam\Works\agenda-dashboard\bin\Release\net8.0-windows
      executable: AgendaDashboard.exe
      args: ~
      position: ~
      toggle window: ~
      window identifier: ~

    Typist:
      location: C:\Users\Arindam\Works\typist\bin\Release\net8.0-windows
      executable: Typist.exe
      args: ~
      position: ~
      toggle window: ~
      window identifier: ~

    LogiTune:
      location: C:\Program Files\Logitech\LogiTune
      executable: LogiTune.exe
      args: ~
      position: ~
      toggle window: ~
      window identifier: ~
    
    Dropbox:
      location: C:\Program Files\WindowsApps\DropboxInc.Dropbox_232.4.5988.0_x64__xbfy0k16fey96
      executable: Dropbox.exe
      args: ~
      position: ~
      toggle window: ~
      window identifier: ~

      #    DesktopInfo64:
      #      location: C:\Program Files\DesktopInfo
      #      executable: DesktopInfo64.exe
      #      args: ~
      #      position: ~
      #      toggle window: ~
      #      window identifier: ~

      #    Telegram:
      #      location: C:\Program Files\Telegram
      #      executable: Telegram.exe
      #      args: ~
      #      position: ~
      #      toggle window: close
      #      window identifier: ~

      #    Signal:
      #      location: C:\Users\Arindam\AppData\Local\Programs\signal-desktop
      #      executable: Signal.exe
      #      args: ~
      #      position: ~
      #      toggle window: close
      #      window identifier: ~

      #    Nearby Share:
      #      location: C:\Program Files\Google\NearbyShare
      #      executable: nearby_share.exe
      #      args: ~
      #      position: ~
      #      toggle window: close
      #      window identifier: ~

      #    Claude:
      #      location: C:\Users\Arindam\AppData\Local\AnthropicClaude
      #      executable: claude.exe
      #      args: ~
      #      position: ~
      #      toggle window: ~
      #      window identifier: ~
