general:
  app_name: Toolbox
  version: 1

hotkeys:
  window:
    action:
      minimize: meta+dash
      toggle_maximize: meta+return
      close: meta+esc
      resize: ctrl+meta+alt+comma
    mode:
      lower_screen: ctrl+meta+alt+M
      upper_screen: ctrl+meta+alt+U
    position:
      right_middle: ctrl+meta+alt+3
      top_right: ctrl+meta+alt+4
      top_middle: ctrl+meta+alt+5
      top_left: ctrl+meta+alt+6
      left_middle: ctrl+meta+alt+7
      bottom_left: ctrl+meta+alt+8
      bottom_middle: ctrl+meta+alt+9
      bottom_right: ctrl+meta+alt+0
    move:
      centre: ctrl+meta+alt+dot
      fast_left: ctrl+meta+alt+left
      fast_right: ctrl+meta+alt+right
      fast_up: ctrl+meta+alt+up
      fast_down: ctrl+meta+alt+down
      slow_left: shift+ctrl+meta+alt+left
      slow_right: shift+ctrl+meta+alt+right
      slow_up: shift+ctrl+meta+alt+up
      slow_down: shift+ctrl+meta+alt+down
